version: '3.8'

services:
  app:
    build: .
    container_name: healthcare-app
    ports:
      - "9000:9000" # Gateway
      - "8000:8000" # Mongo Service
      - "7000:7000" # Postgres Service
    environment:
      - NODE_ENV=development
      # Updated to use postgres:postgres and the correct DB name
      #- POSTGRES_URL=postgres://postgres:postgres@postgres:5432/dbs_project
      #- POSTGRES_URL=postgres://postgres:postgres@host.docker.internal:5432/dbs_project #had to change this omg - looks into dev pg db.
      #- MONGO_URL=mongodb://mongo:27017/healthcare
      - MONGO_URL=mongodb://host.docker.internal:27017/healthcare
      # Explicitly setting these so the 'pg' library finds them
      - PG_HOST=host.docker.internal
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=dbs_project
      - PG_PORT=5432
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:16-alpine
    container_name: pg-engine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbs_project
    ports:
      - "5432:5432"
    # Optional: healthcheck ensures the app waits until DB is actually ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo-engine
    ports:
      - "27017:27017"

  prometheus:
    image: prom/prometheus
    container_name: monitoring-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    container_name: monitoring-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus