global:
  scrape_interval: 5s

scrape_configs:
  # Monitoring your Postgres Proxy Logic
  - job_name: 'postgres-service'
    static_configs:
      - targets: ['app:7000']

  # Monitoring your Mongo Proxy Logic
  - job_name: 'mongo-service'
    static_configs:
      - targets: ['app:8000']

  # Optional: Monitor Gateway overhead
  - job_name: 'gateway'
    static_configs:
      - targets: ['app:9000']